Add null=True to all GeneratedFields in tests.
Snowflake doesn't support non-null Generated Fields, failing with
"SQL compilation error: Cannot set NOT NULL constraint on virtual column FIELD."